services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  api:
    build:
      context: ./rag-local-api
      dockerfile: Dockerfile
    volumes:
      - ./rag-local-api:/app
      - chroma_data:/app/chroma_db_e5 # Nombre claro y separado
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  frontend:
    build:
      context: ./ux-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  chroma_data:
  ollama_data:
